### ISSUE TITLE
Instead of localhost, fetch remote app where it is deployed

### ISSUE THREAD

**Issue by aliwaqar981** [wangel13/dynamic-micro-frontends-with-Nx-and-react#1]
Hi @wangel13 , Thanks for the implementation and that awesome [article](https://taras.one/blog/dynamic-micro-frontends-with-nx-and-react). I've followed the article you've shared to load app with dynamic module federation. But how will I be able to fetch that where my app is deployed instead of localhost?

I've tried pointing the app name to the url where my app is deployed but browers are not allowing me to fetch. I'm attaching screenshot of the issue that I'm facing. 

Any help would be much appreciated. 
<img width="1280" alt="Screen Shot 2022-12-13 at 8 29 27 PM" src="https://user-images.githubusercontent.com/43547698/207376672-7a7936b7-8934-4343-8522-599411a97856.png">

**Comment by wangel13** [comment]
Hello! As i can see your server need to properly configuration of [CORS policy ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) to allow requests from localhost. Or you need to upload app to the same domain.

**Comment by aliwaqar981** [comment]
Hi @wangel13 , my app is deployed on S3 bucket and I've defined CORS policy as follows:
`[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]`

but still no luck

**Comment by wangel13** [comment]
Chrome don't allow to use CORS requests with * on localhost due to security reasons. You can use fake local domain and write it name to CORS policy - [example](https://stackoverflow.com/questions/10883211/why-does-my-http-localhost-cors-origin-not-work/10892392#10892392)

**Comment by aliwaqar981** [comment]
Thanks @wangel13 for your help. It turns out that it wasn't working with dns but when I have gave url which s3 bucket was providing then CORS issues got solved.
